version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: myapp_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #ports:
    #  - "80:3000"

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -e production
    platform: linux

    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - .env  # Load secrets and configs from your .env file
    environment:
      RAILS_ENV: production  # still override for safety

volumes:
  postgres_data:
